# Generated by Django 5.0 on 2023-12-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=70, null=True, verbose_name='Улица')),
                ('number_home', models.IntegerField(blank=True, null=True, verbose_name='Номер дома')),
                ('title_product', models.CharField(max_length=70, verbose_name='Название продукта')),
                ('model_product', models.CharField(blank=True, max_length=30, null=True, verbose_name='Модель продукта')),
                ('product_launch_date', models.DateField(auto_now=True, verbose_name='Дата выхода продукта на рынок')),
                ('debt', models.IntegerField(default=0, verbose_name='Задолженность')),
                ('time_create', models.DateTimeField(auto_now=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Завод',
                'verbose_name_plural': 'Заводы',
            },
        ),
        migrations.CreateModel(
            name='RetailNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=70, null=True, verbose_name='Улица')),
                ('number_home', models.IntegerField(blank=True, null=True, verbose_name='Номер дома')),
                ('title_product', models.CharField(max_length=70, verbose_name='Название продукта')),
                ('model_product', models.CharField(blank=True, max_length=30, null=True, verbose_name='Модель продукта')),
                ('product_launch_date', models.DateField(auto_now=True, verbose_name='Дата выхода продукта на рынок')),
                ('debt', models.IntegerField(default=0, verbose_name='Задолженность')),
                ('time_create', models.DateTimeField(auto_now=True, verbose_name='Время создания')),
                ('provider', models.ManyToManyField(to='electronics_sales.factory', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Розничная сеть',
                'verbose_name_plural': 'Рознечные сети',
            },
        ),
        migrations.CreateModel(
            name='IndividualEntrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('street', models.CharField(max_length=70, verbose_name='Улица')),
                ('number_home', models.IntegerField(blank=True, null=True, verbose_name='Номер дома')),
                ('title_product', models.CharField(max_length=70, verbose_name='Название продукта')),
                ('model_product', models.CharField(blank=True, max_length=30, null=True, verbose_name='Модель продукта')),
                ('product_launch_date', models.DateField(auto_now=True, verbose_name='Дата выхода продукта на рынок')),
                ('debt', models.IntegerField(default=0, verbose_name='Задолженность')),
                ('time_create', models.DateTimeField(auto_now=True, verbose_name='Время создания')),
                ('provider', models.ManyToManyField(to='electronics_sales.retailnetwork', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Индивидуальный предприниматель',
                'verbose_name_plural': 'Индивидуальные предприниматели',
            },
        ),
    ]
