# Generated by Django 5.0 on 2023-12-19 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics_sales', '0002_alter_factory_debt_alter_individualentrepreneur_debt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailnetwork',
            name='provider',
        ),
        migrations.AddField(
            model_name='retailnetwork',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='electronics_sales.factory', verbose_name='Поставщик'),
            preserve_default=False,
        ),
    ]
