# Generated by Django 5.0 on 2023-12-19 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics_sales', '0003_remove_retailnetwork_provider_retailnetwork_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualentrepreneur',
            name='provider',
        ),
        migrations.AddField(
            model_name='individualentrepreneur',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='electronics_sales.factory', verbose_name='Поставщик'),
            preserve_default=False,
        ),
    ]
