# Generated by Django 5.0 on 2023-12-19 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics_sales', '0004_remove_individualentrepreneur_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualentrepreneur',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electronics_sales.retailnetwork', verbose_name='Поставщик'),
        ),
    ]
